create database Project_3;
Use Project_3;

-- i will now import the data to extract meaningful insight

select * from orders_table;
-- i just viewed the entire table.

select count(*) as Total_Orders
from orders_table;
-- i just counted the total rows to know how large the data set is

select * from orders_table
limit 10;

-- basically previewing the first 10 rows to check for consistency in data entry

select distinct OrderID from orders_table;
select distinct CustomerID from orders_table;
select distinct Product from orders_table;
select distinct PaymentMethod from orders_table;
select distinct OrderStatus from orders_table;
select distinct CouponCode from orders_table;
select distinct ReferralSource from orders_table;

-- checked for completness, Accuracy, and consistency in each field, found that there's missing values in the column "CouponCode"

Select CouponCode,
count(*) as Total_coupons
from orders_table
group by CouponCode
order by Total_coupons desc;

-- turns out about 309 records are missing from the column, but using simple business logic, i will able to save the 309 records into a caegory.

set SQL_SAFE_UPDATES=0;
START transaction;

update orders_table
set CouponCode ='No coupon Used'
where CouponCode ='';

Select CouponCode,
count(*) as Total_coupons
from orders_table
group by CouponCode
order by Total_coupons desc;

-- Done!
-- now lets beging to answer basic yet important business questions with the available data

select sum(round(TotalPrice,0)) as Total_revenue From orders_table ;
-- TOTAL REVENUE: $1,264,738 (rounded to 0)

select avg(round(TotalPrice,-1)) as Avg_order_value
from orders_table;
-- AVG REVENUE PER ORDER: $1,053.95 (rounded to 2)

select count(distinct CustomerID) As Total_Customers
From orders_table;
-- The total customers that patronized is ; 1,189

SELECT Product,
sum(round(TotalPrice)) AS Total_Revenue
from orders_table
group by Product
order by Total_Revenue desc;
-- for Total Revenue Generated from Products, check 'Read me' for more information

select product,
sum(Quantity) as Total_Quantity
from orders_table
group by product
order by Total_Quantity desc;
-- For Total quantity of each Products sold, check 'Read me' for more information

select PaymentMethod,
sum(round(TotalPrice)) as Total_Revenue
from orders_table
group by PaymentMethod
order by Total_Revenue desc;
-- For Total revenue generated by each payment method, check 'Read me' for more information

select ReferralSource,
sum(round(TotalPrice)) as Total_Revenue
from orders_table
group by ReferralSource
order by Total_Revenue;
-- For Total revenue generated by each referral source, check 'Read me' for more information
 
 select OrderStatus,
 count(*) as Total_Orders
 from orders_table
 group by OrderStatus
 order by Total_Orders;
-- For Total amount of orders by order status, check 'Read me' for more information

select
 sum(round(TotalPrice)) as Returned_Value
 from orders_table
 where OrderStatus ='Returned';
-- Revenue lost through Returned orders: $243,268

select
sum(round(TotalPrice)) as Cancelled_Value
from orders_table
where OrderStatus='Cancelled';
-- Revenue lost through cancelled orders: $276,390

select ReferralSource,
avg(round(ItemsInCart,0)) as Avg_Cart_Size
From orders_table
group by ReferralSource
order by Avg_Cart_Size desc;
-- Average cart size by referral source, chech 'Read Me' for more information

select CouponCode,
count(*) As Usage_count
from orders_table
group by CouponCode
order by Usage_count;
-- This query aids to calculate the most coupon codes used

select
year(Date) as Order_Year,
sum(round(TotalPrice,0)) as Revenue
from orders_table
group by year(Date)
order by Order_Year;
-- This query aids to calculate the Total revenue generated by each year



